### ISSUE TITLE
Is there anything going on here?

### ISSUE THREAD

**Issue by BenjamenMeyer** [ermo/privateer_wcu#1]
Dear @ermo ,
As an huge fan of the original WC Privateer series and also Gemini Gold (yes, I've played it!) I'm quite interested in knowing whether anything is going on with this project.

More specifically:
[ ] Is development getting moved to Git? - I see this is a clone/import of the sf.net project, is it going to continue here?
[ ] Are you interested in PRs to help start changing out content to talk about GitHub instead of Sf.net?

Please advise.

**Comment by ermo** [comment]
Sorry for the somewhat tardy reply - I've got a lot of things going on IRL atm.

Yes, development of PWCU was moved to Git.  There's not a lot going on with the code (nor that of VegaStrike) for a couple of reasons:

1.  I've never gotten around to getting VS to build on Windows w/the latest no-cost Visual Studio release.

2.  There's no simple/easy way to compile VS on Linux with the patch I made that's floating around on the VS forum.

3.  I haven't patched the VS cmake build configuration files to make them properly python 3.x aware.

(1) is probably necessary for wider user testing and (2) & (3) are necessary for wider development on Linux (which is my main dev environment because of the case-sensitivity ignorance of Windows).

And yes, let's try to look at what we need to change in terms of Sf.net -> GitHub.  It may make sense to keep using the VS forum, though -- unless you have a better idea. =)

**Comment by BenjamenMeyer** [comment]
@ermo thanks for the update. Certainly understand the IRL stuff. I'll take a look at quick things that have minimal impact for SF :arrow_right: GitHub conversion and submit PRs.

I'm fully on Linux as well.

Q: by VS forum you mean https://wiki.vega-strike.org/Main_Page?  If so, agreed; though GitHub certainly has a lot of functionality that could be used for good code management (Projects, PRs, Issues, etc) to centralize development around; you could even host the Wiki stuff in GitHub.

**Comment by ermo** [comment]
A: by VS forum I mean https://forums.vega-strike.org/

Staying within the VS community might make sense in terms of VS engine knowledge. =)

**Comment by BenjamenMeyer** [comment]
Q: Are you going to move to using PRs on GitHub instead of Patches in the forums?

That would significantly enable faster development and contributions.

**Comment by ermo** [comment]
What you suggest sounds like the obvious thing to do, yes.

FWIW, I have no prior experience with Travis and CI in general, but I like the concept in theory.

**Comment by ermo** [comment]
A quick update:

VegaStrike still compiles and runs on my Fedora 25 WS box.

I had to edit the [(fedora-centric) patch I attached in the forum](https://forums.vega-strike.org/viewtopic.php?p=143328#p143328) (python 3.4 -> 3.5) and install python3-devel, but otherwise the [installation instructions on the VS wiki](https://wiki.vega-strike.org/HowTo:Compile_from_SVN_on_Linux) worked just fine.

You'll need to configure VS to use python version 3 in ccmake of course.

**Comment by BenjamenMeyer** [comment]
@ermo cool. I'll try to get it compiling and then push up a PR. Once I can get it compiling myself, then I can look at the docker variant, and setting up something for Travis-CI - I can easily enough get the YAML file together for you if you like; though you'll have to enable that as the repo owner.

So okay...next step for me is getting a compiled environment together. I'll see what I can do this week. Thanks for the links that'll really help in getting going.

**Comment by BenjamenMeyer** [comment]
@ermo another thought....it might be good to setup a "Privateer" or WCU organization on GitHub too; this would (a) keep it off your account if you cared, (b) allow the community to own it easier, and (c) enable you to you more easily bring together the various repositories under a single roof.

Also, trying to build it tonight...I noticed that vegastrike.sf.net is still active on SVN over at sf.net - last commit is in August 2016 even though the website records a few years ago; the svn revision delta is about 100 commits or so. Since git doesn't support having Subversion repositories as an external reference (e.g git submodules), you could setup a git mirror on GitHub of vegastrike that could be kept in sync with what Privateer WCU uses and make it a little easier to manage with a few simple scripts or/and git submodules (git's version of svn:externals).

Any how...working my way through getting a working environment. Any advice would be appreciated.

**Comment by ermo** [comment]
I'm open to any and all suggestions here -- I don't consider myself the "owner" per se, just a temporary steward of sorts who didn't like the idea of seeing all the hard work that has obviously gone into the original Privateer: Universe disappear.

Seeing that you're obviously passionate about getting this thing up to speed with modern dev practices, it might be better if I take a step back and just follow your lead on the organizational side.

I don't have a lot of time to contribute at the moment, as I've just started studying Mech. Eng. which means that I have plenty of ducks to get in a row already.

**In summary:**

- Privateer: Wing Commander Universe organization? I vote yes and I'd be happy to be a co-admin with the caveat that I won't have a lot of time to contribute going forward.
- Sync up the VS source via GitHub for easier code wrangling? I vote yes.
- Travis CI? I vote yes.

Once the above is in order, it may make sense to ensure that things are set up such that anyone interested in playing around with PWCU can do so by following a simple HOWTO here on GitHub.

Once THAT is done, it may also make sense to create a new announcement thread over at the VS forums and link it to<->from here (here = the PWCU organization).

To borrow a phrase from another universe: "Make it so, number one." ;-)

**Comment by BenjamenMeyer** [comment]
Sure thing.

FYI - I've reached out to the VegaStrike team via bug in their system (filed under `shounin`, my SF user) asking about easier collab with for downstream git projects - namely a git mirror of their work; not trying to make them convert, just trying to find an easy way to keep everything going forward.

BTW - Privateer is what got me into computing way back in the day. So yes - very passionate about the game.

**Comment by ermo** [comment]
https://wiki.vega-strike.org/HowTo:Checkout_GIT <- is this of any use to you?

Note that you might need to change the actual address on that page to the new sf URL...

**Comment by BenjamenMeyer** [comment]
Ok, will do.

FYI - I've been talking to the folks on VegaStrike forum; loki is going to send me a disc of the SVN code he has. I'll compare to the fork you have an import to GitHub. They're forming around the VegaStrike org (https://github.com/vegastrike) - I'm not a member there (yet) so it's up in the air where the code will go. So just to keep you up to date on what's going on and why I haven't done more yet.

**Comment by ermo** [comment]
Cool.

I created the pwcu org and added you as owner. Awesome to see that you're stirring the pot and making things happen. =)

@BenjamenMeyer You can catch me at rune dot morling at gmail dot com (I'll delete this line once we've established contact).

**Comment by BenjamenMeyer** [comment]
cool. Email sent from my gmail account.

**Comment by ermo** [comment]
Once you get the original PPU SVN history, what do you plan to do?

FWIW, all I did was basically some (rather time-consuming and annoying) cleanup work on the assets (renaming/sanitizing them to current VS engine standards) and the port to py3.  I made a few smaller adjustments, but PWCU is largely PPU running on the newest VS code.

**Comment by ermo** [comment]
@BenjamenMeyer: Have you given up on this? =)

**Comment by Taose** [comment]
They might not have, they could just be having some down time issues. 

In the mean time, I'm struggling to get VS to work on Windows, simply because I can't find a damn iso that'll work -_-;; 

Once I have a windows iso, probably windows 7, I'll get focused on it.

**Comment by ermo** [comment]
So, just to capture the current status here:

- After getting in touch with @BenjamenMeyer, I propose that the goal should be to get pwcu working on the @Taose VS fork.
- This entails helping ensure that VS-Taose properly supports both py2 and py3 and get it compiling on Fedora/Ubuntu/Arch (and possibly Solus, because I'm involved with that particular distro) via the relevant packaging magic.
- Once that's up and running, the goal is to cross-reference the stuff in Privateer Gemini Gold (the privgold sf svn repo) to see if we can implement any worthwhile changes from that branch, including integrating assets (with permission)

I propose that we discontinue the present project and begin working from the fork in the pwcu org instead (the two code bases are identical as of this writing).

Here's hoping that people will eventually star/watch the pwcu project instead. :)

**Comment by Taose** [comment]
fyi, it currently compiles on both Fedora and Ubuntu, no clue about Arch. It's just a matter of actually getting a release candidate actually released and packaged... not sure if we're going to work with their package managers or just release deb/rpms (entirely depends on interest). 

Make sure to drop in any necessary links so I can follow 'em ;D

**Comment by ermo** [comment]
All future issues should be filed in the pwcu org at https://github.com/pwcu/privateer_wcu/
